<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

if ($this->status()->isSiteRequest()) {
    $labelInfo = $this->siteSetting('property_label_information');
    $showLocale = (bool) $this->siteSetting('show_locale_label', true);
    $filterLocale = $this->siteSetting('filter_locale_values');
    $lang = $this->lang();
    $showValueAnnotations = $this->siteSetting('show_value_annotations');
} else {
    $labelInfo = $this->setting('property_label_information');
    $showLocale = true;
    $filterLocale = false;
    $lang = null;
    $showValueAnnotations = true;
}
$filterLocaleCallback = function ($value) use ($lang) {
    $valueLang = $value->lang();
    return $valueLang == '' || strcasecmp($valueLang, $lang) === 0;
};
?>

<?php
$propertiesNotDisplayed = array('skos:prefLabel', 'crm:P70i_is_documented_in', 'rdfs:seeAlso');//AS THEME OPTION
//'crm:P70i_is_documented_in', 'rdfs:seeAlso' are called in separated bloco "see Also"
//prefLabel is page header
?>

<dl id="resource-values">
<h3>À propos de cet item</h3>
<?php
foreach ($values as $term => $propertyData):
    $propertyValues = $propertyData['values'];
    if (!$propertyValues) continue;
    $property = $propertyData['property'];
    if (in_array($property->term(), $propertiesNotDisplayed)) continue;
    if ($filterLocale) {
        $propertyValues = array_filter($propertyValues, $filterLocaleCallback);
    };
    $propertyLabel = $propertyData['alternate_label'] ?: $translate($property->label());
    echo $this->OnePropValues($property, $propertyValues, $propertyLabel, $labelInfo, $showLocale, $filterLocale, $lang, $showValueAnnotations);
    ?>
<?php endforeach; ?>
</dl>
