<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
//$labelInfo = $this->siteSetting('property_label_information');
$labelInfo = False;

if ($this->status()->isSiteRequest()) {
    $showLocale = (bool) $this->siteSetting('show_locale_label', true);
    $filterLocale = $this->siteSetting('filter_locale_values');
    $lang = $this->lang();
    $showValueAnnotations = (bool) $this->siteSetting('show_value_annotations', false);
} else {
    $showLocale = true;
    $filterLocale = false;
    $lang = null;
    $showValueAnnotations = true;
}
?>
<?php
$propertiesNotDisplayed = array('skos:prefLabel', 'crm:P31_has_modified', 'crm:P108_has_produced', 'crm:P24_transferred_title_of', 'crms:P1_has_conceived');
?>

<?php foreach ($values as $term => $propertyData): ?>
    <?php if (in_array($propertyData['property']->term(), $propertiesNotDisplayed) == false) : ?>
    <?php 
        $propertyLabel = $propertyData['alternate_label'] ?: $translate($property->label());
        echo $this->OnePropValues($propertyData['property'], $propertyData['values'], $propertyLabel, $labelInfo, $showLocale, $filterLocale, $lang);
    ?>
    
    <?php endif; ?>
<?php endforeach; ?>
