<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');

if ($this->status()->isSiteRequest()) {
    $showLocale = (bool) $this->siteSetting('show_locale_label', true);
    $filterLocale = $this->siteSetting('filter_locale_values');
    $lang = $this->lang();
    $showValueAnnotations = (bool) $this->siteSetting('show_value_annotations', false);
} else {
    $showLocale = true;
    $filterLocale = false;
    $lang = null;
    $showValueAnnotations = true;
}
?>
<?php
$propertiesNotDisplayed = array('skos:prefLabel', 'crm:P70i_is_documented_in', 'rdfs:seeAlso');
//'crm:P70i_is_documented_in', 'rdfs:seeAlso' are called in separated bloco "see Also"
//prefLabel is page header
?>

<?php foreach ($values as $term => $propertyData): ?>
    <?php if (in_array($propertyData['property']->term(), $propertiesNotDisplayed) == false) : ?>
    <div class="property" id=<?php echo $propertyData['property']->term(); ?>>
        <h4>
        <?php if ($propertyData['alternate_label']): ?>
        <?php echo $escape($propertyData['alternate_label']); ?>
        <?php else: ?>
        <?php echo $escape($translate($propertyData['property']->label())); ?>
        <?php endif; ?>

        <?php if ('term' === $labelInfo): ?>
        <span class="field-term">(<?php echo $escape($propertyData['property']->term()); ?>)</span>
        <?php elseif ('vocab' === $labelInfo): ?>
        <span class="field-term">(<?php echo $escape($propertyData['property']->vocabulary()->label()); ?>)</span>
        <?php endif; ?>   
        </h4>

        <div class="values">
        <?php foreach ($propertyData['values'] as $value): ?>
            <?php
            $valueType = $value->type();
            $valueLang = $value->lang();
            $valueAnnotation = $value->valueAnnotation();
            $classValue = ['value'];
            $classContent = ['value-content'];
            $isExpandable = false;
            if ('resource' == $valueType || strpos($valueType, 'resource') !== false) {
                $classValue[] = 'resource';
                $classValue[] = $escape($value->valueResource()->resourceName());
            } elseif ('uri' == $valueType) {
                $classValue[] = 'uri';
            };
            if ($propertyData['property']->term() ==  'dcterms:description'){
                $classContent[] = 'smalldesc';
                $isExpandable = true;
            };
            ?>
            <?php if ((!$filterLocale) || ($valueLang == '') || (strcasecmp($valueLang, $lang) == 0)): ?>
            <div class="<?php echo implode(' ', $classValue); ?>" lang="<?php echo $escape($valueLang); ?>">
                <?php if ($showLocale && $valueLang): ?>
                <span class="language"><?php echo $valueLang; ?></span>
                <?php endif; ?>

                <?php if ($isExpandable): ?>
                <input type="checkbox" id="expend" />
                <?php endif; ?>

                <span class="<?php echo implode(' ', $classContent); ?>"><?php echo $filterLocale ? $value->asHtml($lang) : $value->asHtml(); ?></span>

                <?php if ($isExpandable): ?>
                <label for="expend"><?php echo $this->escapeHtml($translate('Read more')); ?>...</label>
                <?php endif; ?>

                


                <?php if(!$value->isPublic()): ?>
                    <span class="o-icon-private" aria-role="tooltip" title="<?php echo $this->escapeHtml($translate('Private')); ?>" aria-label="<?php echo $this->escapeHtml($translate('Private')); ?>"></span>
                <?php endif; ?>
                <?php if ($valueAnnotation && $showValueAnnotations): ?>
                    <a href="#" class="expand" aria-label="<?php echo $this->escapeHtml($translate('Expand')); ?>">
                        <span class="has-annotation o-icon-annotation" aria-role="tooltip" title="<?php echo $this->escapeHtml($translate('Has annotation')); ?>" aria-label="<?php echo $this->escapeHtml($translate('Has annotation')); ?>"></span>
                    </a>
                    <div class="collapsible annotation">
                        <?php echo $valueAnnotation->displayValues(); ?>
                    </div>
                <?php endif; ?>
                <?php $this->trigger('view.show.value', ['value' => $value]); ?>
            </div>
            <?php endif; ?>
        <?php endforeach; ?>
        </div>
    </div>
    <?php endif; ?>
<?php endforeach; ?>
