<?php
$escape = $this->plugin('escapeHtml');
$translate = $this->plugin('translate');
$this->headLink()->appendStylesheet($this->assetUrl('css/resource-page-blocks.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;
$blocks =  $this->resourcePageBlocks($item)->getBlocksList();
?>
<?php echo $this->pageTitle($item->displayTitle(null, $valueLang), 2); ?>

<?php $this->trigger('view.show.before'); ?>

<?php 
//uses a value representation + data in array as given by the values() function of AbstractResourceEntityRepresentation
function writeValueofTerms($termsArray, $itemRep){
    $allValues = $itemRep->values();
    foreach($termsArray as $term){
        $propValue = $allValues[$term];
        if ($propValue){
            ?>
            <div id= <?php echo $term ?> class="property ">
                <dt><?php echo $propValue['alternate_label']; ?></dt>
                <?php foreach ($propValue['values'] as $value): ?>
                    <dd class="value"><?php echo $value->asHtml(); ?></dd>
                <?php endforeach; ?>
            </div>
            <?php
        };
    };
};
?>


<!-- bloc de présentation des informations associées: item-set, see-also, documented in  -->
<?php 
$itemSets = $item->itemSets();
$relatedTerms = array('rdfs:seeAlso', 'crm:P70i_is_documented_in',);
$allValues = $item->values();
if ($itemSets || array_intersect($relatedTerms, array_keys($allValues))): 
ob_start();?>
<dl id="related">
    <h3>Éléments associés</h3>
    <div id= "o:item-set" class="property">
        <dt>Collection(s) contenant l'objet</dt>
        <?php foreach ($itemSets as $itemSet): ?>
        <dd class="value">
            <a href="<?php echo $this->escapeHtml($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(null, $valueLang); ?></a>
        </dd>
        <?php endforeach; ?>
    </div>
    <?php 
    writeValueofTerms($relatedTerms, $resource) 
    ?>
</dl>
<?php 
$blocks['related'] = ob_get_clean();
endif; 
?>


<!-- bloc de présentation des informations administratives de la fiche:
mise à jour, creation, personnes, dates, etc.  -->
<?php ob_start();?>
<dl id="admin-info" class="bloco">
  <h3>Cette fiche d'inventaire</h3>
  <div id = "author-list" class="property">
      <dt>Rédacteur·trice</dt>
      <dd class="value"><?php echo $item->owner()->name(); ?></dd>
  </div>
  <div id = "ficheCreate" class="property">
    <dt>Date de creation</dt>
      <dd class="value"><?php echo $escape($this->i18n()->dateFormat($item->created())); ?></dd>
  </div>
  <div id = "ficheMod" class="property">
      <dt>Date de modification</dt>
        <dd class="value"><?php echo $escape($this->i18n()->dateFormat($item->modified())); ?></dd>
  </div>
  <div id = "mediaRightsHolders" class="property">
      <?php 
      $allrightsHoldersValues = array();
      $alt_label = null;
      foreach ($item->media() as $media):
          $allValues = $media->values();//all metadata of 1 media
          // $this->logger()->info(json_encode($allValues));
          if (isset($allValues['dcterms:rightsHolder'])){
              array_push($allrightsHoldersValues, ...$allValues['dcterms:rightsHolder']['values']);//add all values for dc:rightsHolder for 1 media
              if(!isset($alt_label)){ 
                  $alt_label = $allValues['dcterms:rightsHolder']['alternate_label'];//get the alternate label declared, on the first loop only
              }
          };
      endforeach;
      if ($allrightsHoldersValues){
          ?>
          <div class="property ">
            <dt><?php echo $alt_label; ?></dt>
              <?php foreach(array_unique($allrightsHoldersValues) as $rightHolder):
                    ?>
                  <dd class="value"><?php echo $rightHolder->asHtml(); ?></dd>
              <?php endforeach; ?>
          </div>
          <?php
      };
      ?>
  </div>
</dl>
<?php 
$blocks['adminInfo'] = ob_get_clean();?>


<?php 
function renderBlock($blockName, $blocks){
  // echo $blockName;
  if (array_key_exists($blockName, $blocks)) {
    echo $blocks[$blockName];
  }
}


renderBlock('resourceClass', $blocks);
renderBlock('lightboxGallery', $blocks);
?>




<div id="row">

  <div id="columnA">
    <?php 
    renderBlock('values', $blocks);
    renderBlock('related', $blocks);
    renderBlock('adminInfo', $blocks);
    ?>
  </div>

  <div id="columnB">
    <?php 
    renderBlock('linkedResources', $blocks);
    // renderBlock('testError', $blocks);
    ?>
  </div>
</div>



<?php $this->trigger('view.show.after'); ?>