<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');

$embedMediaSetting = $this->siteSetting('item_media_embed');
$itemMedia = $item->media();
if ($embedMediaSetting == 1) {
    $sortedMedia = $this->SortMedia($itemMedia);
    $lightMedia = (isset($sortedMedia['lightMedia'])) ? $sortedMedia['lightMedia'] : null;
    $otherMedia = (isset($sortedMedia['otherMedia'])) ? $sortedMedia['otherMedia'] : null;
} else {
    $otherMedia = $itemMedia;
}

//queries for the subject values (inverse properties): events related to item in cidoc crm
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->displaySubjectValues($page, 25, $property);
?>

<!-- title of the ressource -->
<?php echo $this->pageTitle($item->displayTitle(), 2); ?> 
<span class= "itemClass">Une entrée de type <?php echo $item->resourceClass()->vocabulary()->prefix() ?>:<?php echo $this->translate($item->displayResourceClassLabel()); ?></span>


<!-- the images -->
<?php if (isset($lightMedia)): ?>
    <?php echo $this->LightGalleryOutput($lightMedia); ?>
<?php endif; ?>




<div class="<?php if($subjectValues){echo"colonne leftCol";}?>">
<!-- note: no columns if nothing in the second column -->

<!-- all the properties -->
<div class="bloco">
    <h3>Item</h3>
    <?php $this->trigger('view.show.before'); ?>
    <?php echo $item->displayValues(); ?>
</div>


<!-- additional info about the ressource -->
<?php 
$otherMediaExists =  (isset($otherMedia) && (count($otherMedia) > 0));
$itemSets = $item->itemSets();
$itemSetExists = (count($itemSets) > 0);
?>
<?php if ($otherMediaExists || $itemSetExists): ?>
    <div class="bloco">
        <h3>Voir aussi</h3>
<?php endif; ?>

    <!-- media other than images -->
    <?php if($otherMediaExists): ?>
        <div id="other-media" class="property">
            <h4><?php echo $this->translate('Other Media'); ?></h4>
            <div class="values">
                <?php foreach($otherMedia as $media): ?>
                <div class="value">
                    <?php echo $media->linkPretty(); ?>
                </div>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif; ?>

    <!-- item set -->
    <?php if($itemSetExists): ?>
        <div class="property ">
            <h4> Collection(s) contenant l'objet</h4>
            <div class="values">
                <?php foreach ($item->itemSets() as $itemSet): ?>
                <div class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif; ?>

<?php if ($otherMediaExists || $itemSetExists): ?>
    </div>
<?php endif; ?>



<!-- info about the omeka record -->
<div class="bloco">
    <h3>Cette fiche d'inventaire</h3>
    <div id="ficheAuth" class="property">
        <h4>Rédacteur·trice</h4>
        <div class="values">
            <div class="value"><a href="<?php echo $escape($item->owner()->url()); ?>"><?php echo $item->owner()->name(); ?></a></div>
        </div>
    </div>
    <div id="ficheCreate" class="property">
        <h4>Date de creation</h4>
        <div class="values">
            <div class="value"><?php echo $escape($this->i18n()->dateFormat($item->created())); ?></div>
        </div>
    </div>
    <div id="ficheCreate" class="property">
        <h4>Date modification</h4>
        <div class="values">
            <div class="value"><?php echo $escape($this->i18n()->dateFormat($item->modified())); ?></div>
        </div>
    </div>
</div>

</div><!-- column div closing -->

<div class="colonne rightCol">


<!-- function to build event display -->
<?php
//todo: class inheritance with external data
//todo: ability to get the next class (e.g.: Creation -> DesignOrProcedure -> HumanMadeObjet : we need to reach Creation item)
function writeEvent($classTerm, $displayTerm, $item) {
    foreach ($item->subjectValues() as $term => $subjectValues) {
        foreach ($subjectValues as $subjectValue) {
            //todo: ordonner finement ensuite par date dans chaque catégorie 
            $subjectResource = $subjectValue->resource();
            $subjectProperty = $subjectValue->property();
            $subjectResourceClass = $subjectResource->resourceClass()->term();
            $subjectResourceURL = $subjectResource->url();
            if ($subjectResourceClass == $classTerm) {
                //echo $subjectResourceClass;
                ?>
                <div class="bloco">
                    <?php
                    echo sprintf('<h3><a href=%s>%s</a></h3>', $subjectResourceURL, $displayTerm);
                    // echo sprintf('<h3>%s</h3>', $subjectResource->displayResourceClassLabel());
                    $options = array('viewName' => 'common/resource-values_event-in-item',);
                    echo $subjectResource->displayValues($options);
                    ?>
                </div>
                <?php
            }
        }
    }
};
?>

<!-- subject values printing -->

<?php if ($subjectValues): ?>
    <div id="item-linked" >
        <?php 
        //todo: create an ui hook for the ressources class to display
        if ($item->resourceClass()->term() == 'crm:E22_Human-Made_Object'){
            
            writeEvent('crm:E12_Production', 'Production', $item);
            writeEvent('crm:E11_Modification', 'Modification', $item);
            writeEvent('crm:E8_Acquisition', 'Acquisition', $item);
        }
        ?>
    </div>
<?php endif; ?>

</div><!-- column div closing -->

<?php $this->trigger('view.show.after'); ?>
