<?php
$itemMedia = $item->media();
?>


<!-- info about the omeka record -->
<div class="bloco">
    <h3>Cette fiche d'inventaire</h3>
    <div id="ficheAuth" class="property">
        <h4>Rédacteur·trice</h4>
        <div class="values">
            <!-- <div class="value"><a href="<?php // echo $escape($item->owner()->url()); ?>"><?php // echo $item->owner()->name(); ?></a></div> -->
            <div class="value"><?php echo $item->owner()->name(); ?></div>
        </div>
    </div>
    <div id="ficheCreate" class="property">
        <h4>Date de creation</h4>
        <div class="values">
            <div class="value"><?php echo $escape($this->i18n()->dateFormat($item->created())); ?></div>
        </div>
    </div>
    <div id="ficheCreate" class="property">
        <h4>Date de modification</h4>
        <div class="values">
            <div class="value"><?php echo $escape($this->i18n()->dateFormat($item->modified())); ?></div>
        </div>
    </div>
    <div id="mediaRightsHolders" class="property">
        <?php 
        $allrightsHoldersValues = array();
        $alt_label = null;
        foreach ($itemMedia as $media):
            $allValues = $media->values();//all metadata of 1 media
            if (isset($allValues['dcterms:rightsHolder'])){
                array_push($allrightsHoldersValues, ...$allValues['dcterms:rightsHolder']['values']);//add all values for dc:rightsHolder for 1 media
                if(!isset($alt_label)){ 
                    $alt_label = $allValues['dcterms:rightsHolder']['alternate_label'];//get the alternate label declared, on the first loop only
                }
            };
        endforeach;
        if ($allrightsHoldersValues){
            ?>
            <div class="property ">
                <h4><?php echo $alt_label; ?></h4>
                <div class="values">
                    <?php foreach(array_unique($allrightsHoldersValues) as $rightHolder):
                         ?>
                        <div class="value"><?php echo $rightHolder->asHtml(); ?></div>
                    <?php endforeach; ?>
                </div>
            </div>
            <?php
        };
        ?>
    </div>
</div>