<?php if ($itemSets): ?>
<dl id="item-sets">
    <div id= "o:item-set" class="property">
        <dt>Collections</dt>
        <?php foreach ($itemSets as $itemSet): ?>
        <dd class="value">
            <a href="<?php echo $this->escapeHtml($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(null, $valueLang); ?></a>
        </dd>
        <?php endforeach; ?>
    </div>
</dl>
<?php endif; ?>
