<?php
$resourceClass = $resource->resourceClass();
if ($this->status()->isSiteRequest()) {
    $labelInfo = $this->siteSetting('property_label_information');
}
else {
    $labelInfo = $this->setting('property_label_information');
}

if ('term' === $labelInfo) {
    $displayLabelInfo = $resourceClass->term();
} elseif ('vocab' === $labelInfo) {
    $displayLabelInfo = $resourceClass->vocabulary()->label();
} else {
    $displayLabelInfo = null;
};
?>

<?php if ($resourceClass): ?>
<div class= "property">
        Un item de type <b><?php echo $this->escapeHtml($resourceClass->label()) ?></b>
        <?php if ($displayLabelInfo) : ?>
            <span class="field-term">(<?php echo $this->escapeHtml($displayLabelInfo); ?>)</span>
        <?php endif; ?>
</div>
<?php endif; ?>


